# Generated by Django 3.2.3 on 2021-06-10 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_electricitydetail_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitydetail',
            name='date_stamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='electricitydetail',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
